import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { AppHeader } from '@/widgets/app-header';
import { ApolloProvider } from './_providers';
import Minetruck from '@/entities/minetruck';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ApolloProvider>
                    <AntdRegistry>
                        <AppHeader variant={'public'} />
                        <Minetruck></Minetruck>
                    </AntdRegistry>
                </ApolloProvider>
            </body>
        </html>
    );
}
